# Site settings
title: Jekyll Writer
email: sneezry@sneezry.com
description: "A Jekyll Blog for MoteDown."
baseurl: ""
url: "https://jekyll-writer.github.io"
twitter_username: sneezry
github_username:  sneezry

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap